name: intel-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.23.5          # ← pin in the safe range
  - pillow
  - tqdm
  - scikit-learn
  - scikeras
  - pip
  - pip:
      - tensorflow-macos==2.11.0
      - tensorflow-metal==0.6.0
      - chardet
  # TO UPDATE THIS ENV, ADD OR REMOVE PACKAGES, AND THEN RUN THIS:
  # `conda env update --name intel-env --file environment.yml --prune`